apiVersion: v1
kind: Secret
metadata:
  name: platform-secrets
  namespace: face-attendance
type: Opaque
data:
  # echo -n "postgresql://dbadmin:SecretPassword123@postgres-service:5432/face_attendance_db" | base64
  DATABASE_URL: cG9zdGdyZXNxbDovL2RiYWRtaW46U2VjcmV0UGFzc3dvcmQxMjNAcG9zdGdyZXMtc2VydmljZTo1NDMyL2ZhY2VfYXR0ZW5kYW5jZV9kYg==
  # echo -n "SuperSecretKeyAtLeast32CharsLongMustBeComplex!" | base64
  JWT_SECRET: U3VwZXJTZWNyZXRLZXlBdExlYXN0MzJDaGFyc0xvbmdNdXN0QmVDb21wbGV4IQ==
  # echo -n "0x70997970C51812dc3A010C7d01b50e0d17dc79C8" | base64
  BLOCKCHAIN_PRIVATE_KEY: MHg3MDk5Nzk3MEM1MTgxMmRjM0EwMTBDN2QwMWI1MGUwZDE3ZGM3OUM4
