"""autogen: rbac & analytics

Revision ID: 173d20e70930
Revises: phase3_rbac_analytics
Create Date: 2026-06-04 10:04:53.760055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = '173d20e70930'
down_revision: Union[str, Sequence[str], None] = 'phase3_rbac_analytics'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attendance_logs', 'check_out',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='NULL until clock-out',
               existing_comment='NULL until the user clocks out — supports dual-punch',
               existing_nullable=True)
    op.alter_column('attendance_logs', 'status',
               existing_type=sa.VARCHAR(length=30),
               comment='on_time|late|early|absent|excused|manual_override',
               existing_comment='on_time | late | early | absent | excused | manual_override',
               existing_nullable=False)
    op.alter_column('attendance_logs', 'emotion',
               existing_type=sa.VARCHAR(length=30),
               comment=None,
               existing_comment='happy | neutral | sad | angry | stressed | fear | surprise',
               existing_nullable=True)
    op.alter_column('attendance_logs', 'emotion_score',
               existing_type=sa.NUMERIC(precision=4, scale=3),
               comment=None,
               existing_comment='DeepFace confidence score 0.000–1.000',
               existing_nullable=True)
    op.alter_column('attendance_logs', 'is_live',
               existing_type=sa.INTEGER(),
               comment='1=liveness passed',
               existing_comment='1 = liveness check passed (blink / head-turn detected)',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('attendance_logs', 'recognition_distance',
               existing_type=sa.NUMERIC(precision=6, scale=4),
               comment='pgvector cosine distance at match',
               existing_comment='Cosine distance at match time — for retrospective audit',
               existing_nullable=True)
    op.alter_column('attendance_logs', 'source',
               existing_type=sa.VARCHAR(length=20),
               comment='ai|manual|edge|bulk_import',
               existing_comment='ai | manual | edge | bulk_import',
               existing_nullable=False,
               existing_server_default=sa.text("'ai'::character varying"))
    op.alter_column('attendance_logs', 'geofence_pass',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='1 = within geofence, 0 = outside, NULL = geofencing disabled',
               existing_nullable=True)
    op.alter_column('attendance_logs', 'is_deleted',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='0 = active, 1 = soft-deleted',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('blockchain_audit_logs', 'ref_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Primary key of the source row being sealed',
               existing_nullable=False)
    op.alter_column('blockchain_audit_logs', 'ref_type',
               existing_type=sa.VARCHAR(length=50),
               comment='attendance|manual_override|org_onboard|user_enroll|key_revoke',
               existing_comment='attendance | manual_override | org_onboard | user_enroll | key_revoke',
               existing_nullable=False)
    op.alter_column('blockchain_audit_logs', 'record_hash',
               existing_type=sa.VARCHAR(length=64),
               comment="SHA-256 hex — pgcrypto encode(digest(),'hex')",
               existing_comment="SHA-256 hex digest of source row (pgcrypto: encode(digest(...,'sha256'),'hex'))",
               existing_nullable=False)
    op.alter_column('blockchain_audit_logs', 'tx_hash',
               existing_type=sa.VARCHAR(length=128),
               comment=None,
               existing_comment='On-chain transaction hash (Polygon / Ganache)',
               existing_nullable=True)
    op.alter_column('blockchain_audit_logs', 'block_number',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='Block number on the L2 chain for independent verification',
               existing_nullable=True)
    op.alter_column('departments', 'is_deleted',
               existing_type=sa.INTEGER(),
               comment='0=active, 1=soft-deleted',
               existing_comment='0 = active, 1 = soft-deleted — never hard DELETE',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('face_embeddings', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=128),
               comment='FaceNet 128-d — pgvector VECTOR(128)',
               existing_comment='FaceNet 128-d embedding — pgvector VECTOR type',
               existing_nullable=False)
    op.alter_column('face_embeddings', 'zkp_public_commitment',
               existing_type=sa.VARCHAR(length=512),
               comment='Schnorr P=x·G — no raw biometric stored',
               existing_comment='Schnorr ZKP public commitment P = x·G (no raw biometric)',
               existing_nullable=True)
    op.alter_column('face_embeddings', 'model_name',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Facenet | ArcFace | InsightFace',
               existing_nullable=False,
               existing_server_default=sa.text("'Facenet'::character varying"))
    op.alter_column('face_embeddings', 'is_active',
               existing_type=sa.INTEGER(),
               comment='1=current 0=superseded by re-enrollment',
               existing_comment='1 = current active embedding, 0 = superseded by re-enrollment',
               existing_nullable=False,
               existing_server_default=sa.text('1'))
    op.drop_index(op.f('idx_face_embeddings_hnsw'), table_name='face_embeddings', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.alter_column('manual_overrides', 'target_user_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='The employee whose attendance is being corrected',
               existing_nullable=False)
    op.alter_column('manual_overrides', 'admin_user_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='The admin who authorized the correction',
               existing_nullable=False)
    op.alter_column('manual_overrides', 'attendance_log_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='The original log being corrected — NULL if no prior log exists',
               existing_nullable=True)
    op.alter_column('manual_overrides', 'reason_category',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='device_malfunction | forgot_phone | network_outage | camera_failure | admin_correction | other',
               existing_nullable=False)
    op.alter_column('manual_overrides', 'override_status',
               existing_type=sa.VARCHAR(length=30),
               comment=None,
               existing_comment='Final status written to the corrected attendance row',
               existing_nullable=False)
    op.alter_column('manual_overrides', 'override_notes',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Free-text justification from the admin',
               existing_nullable=True)
    op.alter_column('manual_overrides', 'employee_approved',
               existing_type=sa.INTEGER(),
               comment='0=pending ZKP approval 1=approved',
               existing_comment='0 = pending employee ZKP approval, 1 = approved',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('manual_overrides', 'approved_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp of employee ZKP approval — NULL until approved',
               existing_nullable=True)
    op.create_index('ix_override_pending', 'manual_overrides', ['target_user_id'], unique=False, postgresql_where=sa.text('employee_approved = 0'))
    op.alter_column('monthly_growth_summary', 'month_year',
               existing_type=sa.VARCHAR(length=7),
               comment="'2026-03'",
               existing_comment="ISO format: '2026-03'",
               existing_nullable=False)
    op.alter_column('monthly_growth_summary', 'avg_emotion_score',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               comment=None,
               existing_comment='0.0000–1.0000 positive sentiment ratio',
               existing_nullable=True)
    op.alter_column('monthly_growth_summary', 'stress_event_count',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment="Count of check-ins where emotion IN ('sad','stressed')",
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('monthly_growth_summary', 'burnout_risk_score',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               comment='>40 triggers AI Nudge',
               existing_comment='Polars burnout model output 0–100',
               existing_nullable=True)
    op.alter_column('monthly_growth_summary', 'productivity_score',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               comment=None,
               existing_comment='Output velocity synced from Jira / GitHub (0–100)',
               existing_nullable=True)
    op.alter_column('monthly_growth_summary', 'growth_index',
               existing_type=sa.NUMERIC(precision=6, scale=2),
               comment=None,
               existing_comment='Percentage change in productivity vs prior month',
               existing_nullable=True)
    op.drop_index(op.f('ix_monthly_burnout'), table_name='monthly_growth_summary', postgresql_where='(burnout_risk_score > (40)::numeric)')
    op.drop_constraint(op.f('uq_monthly_summary_user_month'), 'monthly_growth_summary', type_='unique')
    op.create_index('ix_monthly_burnout_risk', 'monthly_growth_summary', ['burnout_risk_score'], unique=False, postgresql_where=sa.text('burnout_risk_score > 40'))
    op.create_unique_constraint('uq_monthly_user_month', 'monthly_growth_summary', ['user_id', 'month_year'])
    op.alter_column('offline_sync_queue', 'payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Raw check-in payload as captured by the edge device',
               existing_nullable=False)
    op.alter_column('offline_sync_queue', 'captured_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp recorded by the device at capture time (before sync)',
               existing_nullable=False)
    op.alter_column('offline_sync_queue', 'synced',
               existing_type=sa.INTEGER(),
               comment='0=pending 1=synced',
               existing_comment='0 = pending, 1 = successfully synced to attendance_logs',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('offline_sync_queue', 'error_msg',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='NULL on success, exception message on failure',
               existing_nullable=True)
    op.alter_column('org_api_keys', 'key_hash',
               existing_type=sa.VARCHAR(length=255),
               comment='SHA-256 of raw key — pgcrypto digest()',
               existing_comment='SHA-256 hash of the raw API key (pgcrypto: digest())',
               existing_nullable=False)
    op.alter_column('org_api_keys', 'scope',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='write_checkin | read_report | admin',
               existing_nullable=False,
               existing_server_default=sa.text("'write_checkin'::character varying"))
    op.alter_column('org_api_keys', 'rate_limit',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Maximum requests per minute for this device',
               existing_nullable=False,
               existing_server_default=sa.text('100'))
    # op.execute("ALTER TABLE org_api_keys ALTER COLUMN is_revoked DROP DEFAULT;")
    # op.alter_column('org_api_keys', 'is_revoked',
    #            existing_type=sa.BOOLEAN(),
    #            type_=sa.Integer(),
    #            existing_nullable=False,
    #            postgresql_using='CASE WHEN is_revoked THEN 1 ELSE 0 END')
    # op.execute("ALTER TABLE org_api_keys ALTER COLUMN is_revoked SET DEFAULT 0;")
    op.create_index(op.f('ix_org_api_keys_id'), 'org_api_keys', ['id'], unique=False)
    op.alter_column('organizations', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Tenant UUID — also used as the PostgreSQL schema name suffix',
               existing_nullable=False,
               existing_server_default=sa.text('uuid_generate_v4()'))
    op.alter_column('organizations', 'legal_id',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Government-issued company registration number',
               existing_nullable=False)
    op.alter_column('organizations', 'blockchain_root_key',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Genesis hash anchored on L2 chain at onboarding',
               existing_nullable=True)
    op.alter_column('organizations', 'zkp_threshold',
               existing_type=sa.NUMERIC(precision=4, scale=2),
               comment=None,
               existing_comment='Minimum ZKP match confidence (0.00–1.00)',
               existing_nullable=False,
               existing_server_default=sa.text('0.98'))
    op.alter_column('roles', 'name',
               existing_type=sa.VARCHAR(length=50),
               comment='Admin | Manager | Employee | Device',
               existing_nullable=False)
    op.alter_column('roles', 'permissions',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='JSON array of allowed route/action strings',
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('shifts', 'shift_name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='e.g. Morning Batch | Night Shift',
               existing_nullable=False)
    op.alter_column('shifts', 'start_time',
               existing_type=postgresql.TIME(),
               comment=None,
               existing_comment='e.g. 09:00:00',
               existing_nullable=False)
    op.alter_column('shifts', 'end_time',
               existing_type=postgresql.TIME(),
               comment=None,
               existing_comment='e.g. 17:00:00',
               existing_nullable=False)
    op.alter_column('shifts', 'grace_period_mins',
               existing_type=sa.INTEGER(),
               comment="Minutes after start before 'Late'",
               existing_comment="Minutes after start_time before check-in becomes 'late'",
               existing_nullable=False,
               existing_server_default=sa.text('5'))
    op.alter_column('shifts', 'buffer_mins',
               existing_type=sa.INTEGER(),
               comment='Minutes before start for early clock-in',
               existing_comment='Minutes before start_time that early clock-in is allowed',
               existing_nullable=False,
               existing_server_default=sa.text('15'))
    op.alter_column('shifts', 'break_deduct_mins',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Auto-deducted lunch break minutes from total hours',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('users', 'enrollment_token',
               existing_type=sa.VARCHAR(length=255),
               comment='pgcrypto gen_random_bytes — one-time ZKP onboarding link',
               existing_comment='One-time enrollment link token (pgcrypto: gen_random_bytes)',
               existing_nullable=True,
               existing_server_default=sa.text("encode(gen_random_bytes(32), 'hex'::text)"))
    op.alter_column('users', 'token_expires',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Enrollment token expiry — NULL after ZKP enrollment completes',
               existing_nullable=True)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               comment='bcrypt passlib — mirrors pgcrypto crypt()',
               existing_comment="bcrypt hash — pgcrypto: crypt(plain, gen_salt('bf', 12))",
               existing_nullable=False)
    op.alter_column('users', 'is_deleted',
               existing_type=sa.INTEGER(),
               comment='0=active 1=soft-deleted',
               existing_comment='0 = active, 1 = soft-deleted',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('users', 'is_active',
               existing_type=sa.INTEGER(),
               comment='1=active 0=suspended',
               existing_comment='1 = active, 0 = suspended',
               existing_nullable=False,
               existing_server_default=sa.text('1'))
    op.drop_index(op.f('ix_users_active'), table_name='users', postgresql_where='(is_deleted = 0)')
    op.create_index('ix_users_active_org', 'users', ['org_id'], unique=False, postgresql_where=sa.text('is_deleted = 0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_active_org', table_name='users', postgresql_where=sa.text('is_deleted = 0'))
    op.create_index(op.f('ix_users_active'), 'users', ['org_id'], unique=False, postgresql_where='(is_deleted = 0)')
    op.alter_column('users', 'is_active',
               existing_type=sa.INTEGER(),
               comment='1 = active, 0 = suspended',
               existing_comment='1=active 0=suspended',
               existing_nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('users', 'is_deleted',
               existing_type=sa.INTEGER(),
               comment='0 = active, 1 = soft-deleted',
               existing_comment='0=active 1=soft-deleted',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               comment="bcrypt hash — pgcrypto: crypt(plain, gen_salt('bf', 12))",
               existing_comment='bcrypt passlib — mirrors pgcrypto crypt()',
               existing_nullable=False)
    op.alter_column('users', 'token_expires',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Enrollment token expiry — NULL after ZKP enrollment completes',
               existing_nullable=True)
    op.alter_column('users', 'enrollment_token',
               existing_type=sa.VARCHAR(length=255),
               comment='One-time enrollment link token (pgcrypto: gen_random_bytes)',
               existing_comment='pgcrypto gen_random_bytes — one-time ZKP onboarding link',
               existing_nullable=True,
               existing_server_default=sa.text("encode(gen_random_bytes(32), 'hex'::text)"))
    op.alter_column('shifts', 'break_deduct_mins',
               existing_type=sa.INTEGER(),
               comment='Auto-deducted lunch break minutes from total hours',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('shifts', 'buffer_mins',
               existing_type=sa.INTEGER(),
               comment='Minutes before start_time that early clock-in is allowed',
               existing_comment='Minutes before start for early clock-in',
               existing_nullable=False,
               existing_server_default=sa.text('15'))
    op.alter_column('shifts', 'grace_period_mins',
               existing_type=sa.INTEGER(),
               comment="Minutes after start_time before check-in becomes 'late'",
               existing_comment="Minutes after start before 'Late'",
               existing_nullable=False,
               existing_server_default=sa.text('5'))
    op.alter_column('shifts', 'end_time',
               existing_type=postgresql.TIME(),
               comment='e.g. 17:00:00',
               existing_nullable=False)
    op.alter_column('shifts', 'start_time',
               existing_type=postgresql.TIME(),
               comment='e.g. 09:00:00',
               existing_nullable=False)
    op.alter_column('shifts', 'shift_name',
               existing_type=sa.VARCHAR(length=100),
               comment='e.g. Morning Batch | Night Shift',
               existing_nullable=False)
    op.alter_column('roles', 'permissions',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='JSON array of allowed route/action strings',
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('roles', 'name',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Admin | Manager | Employee | Device',
               existing_nullable=False)
    op.alter_column('organizations', 'zkp_threshold',
               existing_type=sa.NUMERIC(precision=4, scale=2),
               comment='Minimum ZKP match confidence (0.00–1.00)',
               existing_nullable=False,
               existing_server_default=sa.text('0.98'))
    op.alter_column('organizations', 'blockchain_root_key',
               existing_type=sa.VARCHAR(length=255),
               comment='Genesis hash anchored on L2 chain at onboarding',
               existing_nullable=True)
    op.alter_column('organizations', 'legal_id',
               existing_type=sa.VARCHAR(length=100),
               comment='Government-issued company registration number',
               existing_nullable=False)
    op.alter_column('organizations', 'id',
               existing_type=sa.UUID(),
               comment='Tenant UUID — also used as the PostgreSQL schema name suffix',
               existing_nullable=False,
               existing_server_default=sa.text('uuid_generate_v4()'))
    op.drop_index(op.f('ix_org_api_keys_id'), table_name='org_api_keys')
    # op.execute("ALTER TABLE org_api_keys ALTER COLUMN is_revoked DROP DEFAULT;")
    # op.alter_column('org_api_keys', 'is_revoked',
    #            existing_type=sa.Integer(),
    #            type_=sa.BOOLEAN(),
    #            existing_nullable=False,
    #            postgresql_using='CASE WHEN is_revoked = 1 THEN true ELSE false END')
    # op.execute("ALTER TABLE org_api_keys ALTER COLUMN is_revoked SET DEFAULT false;")
    op.alter_column('org_api_keys', 'rate_limit',
               existing_type=sa.INTEGER(),
               comment='Maximum requests per minute for this device',
               existing_nullable=False,
               existing_server_default=sa.text('100'))
    op.alter_column('org_api_keys', 'scope',
               existing_type=sa.VARCHAR(length=50),
               comment='write_checkin | read_report | admin',
               existing_nullable=False,
               existing_server_default=sa.text("'write_checkin'::character varying"))
    op.alter_column('org_api_keys', 'key_hash',
               existing_type=sa.VARCHAR(length=255),
               comment='SHA-256 hash of the raw API key (pgcrypto: digest())',
               existing_comment='SHA-256 of raw key — pgcrypto digest()',
               existing_nullable=False)
    op.alter_column('offline_sync_queue', 'error_msg',
               existing_type=sa.TEXT(),
               comment='NULL on success, exception message on failure',
               existing_nullable=True)
    op.alter_column('offline_sync_queue', 'synced',
               existing_type=sa.INTEGER(),
               comment='0 = pending, 1 = successfully synced to attendance_logs',
               existing_comment='0=pending 1=synced',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('offline_sync_queue', 'captured_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp recorded by the device at capture time (before sync)',
               existing_nullable=False)
    op.alter_column('offline_sync_queue', 'payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Raw check-in payload as captured by the edge device',
               existing_nullable=False)
    op.drop_constraint('uq_monthly_user_month', 'monthly_growth_summary', type_='unique')
    op.drop_index('ix_monthly_burnout_risk', table_name='monthly_growth_summary', postgresql_where=sa.text('burnout_risk_score > 40'))
    op.create_unique_constraint(op.f('uq_monthly_summary_user_month'), 'monthly_growth_summary', ['user_id', 'month_year'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_monthly_burnout'), 'monthly_growth_summary', ['burnout_risk_score'], unique=False, postgresql_where='(burnout_risk_score > (40)::numeric)')
    op.alter_column('monthly_growth_summary', 'growth_index',
               existing_type=sa.NUMERIC(precision=6, scale=2),
               comment='Percentage change in productivity vs prior month',
               existing_nullable=True)
    op.alter_column('monthly_growth_summary', 'productivity_score',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               comment='Output velocity synced from Jira / GitHub (0–100)',
               existing_nullable=True)
    op.alter_column('monthly_growth_summary', 'burnout_risk_score',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               comment='Polars burnout model output 0–100',
               existing_comment='>40 triggers AI Nudge',
               existing_nullable=True)
    op.alter_column('monthly_growth_summary', 'stress_event_count',
               existing_type=sa.INTEGER(),
               comment="Count of check-ins where emotion IN ('sad','stressed')",
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('monthly_growth_summary', 'avg_emotion_score',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               comment='0.0000–1.0000 positive sentiment ratio',
               existing_nullable=True)
    op.alter_column('monthly_growth_summary', 'month_year',
               existing_type=sa.VARCHAR(length=7),
               comment="ISO format: '2026-03'",
               existing_comment="'2026-03'",
               existing_nullable=False)
    op.drop_index('ix_override_pending', table_name='manual_overrides', postgresql_where=sa.text('employee_approved = 0'))
    op.alter_column('manual_overrides', 'approved_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp of employee ZKP approval — NULL until approved',
               existing_nullable=True)
    op.alter_column('manual_overrides', 'employee_approved',
               existing_type=sa.INTEGER(),
               comment='0 = pending employee ZKP approval, 1 = approved',
               existing_comment='0=pending ZKP approval 1=approved',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('manual_overrides', 'override_notes',
               existing_type=sa.TEXT(),
               comment='Free-text justification from the admin',
               existing_nullable=True)
    op.alter_column('manual_overrides', 'override_status',
               existing_type=sa.VARCHAR(length=30),
               comment='Final status written to the corrected attendance row',
               existing_nullable=False)
    op.alter_column('manual_overrides', 'reason_category',
               existing_type=sa.VARCHAR(length=100),
               comment='device_malfunction | forgot_phone | network_outage | camera_failure | admin_correction | other',
               existing_nullable=False)
    op.alter_column('manual_overrides', 'attendance_log_id',
               existing_type=sa.INTEGER(),
               comment='The original log being corrected — NULL if no prior log exists',
               existing_nullable=True)
    op.alter_column('manual_overrides', 'admin_user_id',
               existing_type=sa.INTEGER(),
               comment='The admin who authorized the correction',
               existing_nullable=False)
    op.alter_column('manual_overrides', 'target_user_id',
               existing_type=sa.INTEGER(),
               comment='The employee whose attendance is being corrected',
               existing_nullable=False)
    op.create_index(op.f('idx_face_embeddings_hnsw'), 'face_embeddings', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.alter_column('face_embeddings', 'is_active',
               existing_type=sa.INTEGER(),
               comment='1 = current active embedding, 0 = superseded by re-enrollment',
               existing_comment='1=current 0=superseded by re-enrollment',
               existing_nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('face_embeddings', 'model_name',
               existing_type=sa.VARCHAR(length=50),
               comment='Facenet | ArcFace | InsightFace',
               existing_nullable=False,
               existing_server_default=sa.text("'Facenet'::character varying"))
    op.alter_column('face_embeddings', 'zkp_public_commitment',
               existing_type=sa.VARCHAR(length=512),
               comment='Schnorr ZKP public commitment P = x·G (no raw biometric)',
               existing_comment='Schnorr P=x·G — no raw biometric stored',
               existing_nullable=True)
    op.alter_column('face_embeddings', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=128),
               comment='FaceNet 128-d embedding — pgvector VECTOR type',
               existing_comment='FaceNet 128-d — pgvector VECTOR(128)',
               existing_nullable=False)
    op.alter_column('departments', 'is_deleted',
               existing_type=sa.INTEGER(),
               comment='0 = active, 1 = soft-deleted — never hard DELETE',
               existing_comment='0=active, 1=soft-deleted',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('blockchain_audit_logs', 'block_number',
               existing_type=sa.BIGINT(),
               comment='Block number on the L2 chain for independent verification',
               existing_nullable=True)
    op.alter_column('blockchain_audit_logs', 'tx_hash',
               existing_type=sa.VARCHAR(length=128),
               comment='On-chain transaction hash (Polygon / Ganache)',
               existing_nullable=True)
    op.alter_column('blockchain_audit_logs', 'record_hash',
               existing_type=sa.VARCHAR(length=64),
               comment="SHA-256 hex digest of source row (pgcrypto: encode(digest(...,'sha256'),'hex'))",
               existing_comment="SHA-256 hex — pgcrypto encode(digest(),'hex')",
               existing_nullable=False)
    op.alter_column('blockchain_audit_logs', 'ref_type',
               existing_type=sa.VARCHAR(length=50),
               comment='attendance | manual_override | org_onboard | user_enroll | key_revoke',
               existing_comment='attendance|manual_override|org_onboard|user_enroll|key_revoke',
               existing_nullable=False)
    op.alter_column('blockchain_audit_logs', 'ref_id',
               existing_type=sa.INTEGER(),
               comment='Primary key of the source row being sealed',
               existing_nullable=False)
    op.alter_column('attendance_logs', 'is_deleted',
               existing_type=sa.INTEGER(),
               comment='0 = active, 1 = soft-deleted',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('attendance_logs', 'geofence_pass',
               existing_type=sa.INTEGER(),
               comment='1 = within geofence, 0 = outside, NULL = geofencing disabled',
               existing_nullable=True)
    op.alter_column('attendance_logs', 'source',
               existing_type=sa.VARCHAR(length=20),
               comment='ai | manual | edge | bulk_import',
               existing_comment='ai|manual|edge|bulk_import',
               existing_nullable=False,
               existing_server_default=sa.text("'ai'::character varying"))
    op.alter_column('attendance_logs', 'recognition_distance',
               existing_type=sa.NUMERIC(precision=6, scale=4),
               comment='Cosine distance at match time — for retrospective audit',
               existing_comment='pgvector cosine distance at match',
               existing_nullable=True)
    op.alter_column('attendance_logs', 'is_live',
               existing_type=sa.INTEGER(),
               comment='1 = liveness check passed (blink / head-turn detected)',
               existing_comment='1=liveness passed',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('attendance_logs', 'emotion_score',
               existing_type=sa.NUMERIC(precision=4, scale=3),
               comment='DeepFace confidence score 0.000–1.000',
               existing_nullable=True)
    op.alter_column('attendance_logs', 'emotion',
               existing_type=sa.VARCHAR(length=30),
               comment='happy | neutral | sad | angry | stressed | fear | surprise',
               existing_nullable=True)
    op.alter_column('attendance_logs', 'status',
               existing_type=sa.VARCHAR(length=30),
               comment='on_time | late | early | absent | excused | manual_override',
               existing_comment='on_time|late|early|absent|excused|manual_override',
               existing_nullable=False)
    op.alter_column('attendance_logs', 'check_out',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='NULL until the user clocks out — supports dual-punch',
               existing_comment='NULL until clock-out',
               existing_nullable=True)
    # ### end Alembic commands ###
