"""Initial migration

Revision ID: 3eaaee4c0cc5
Revises: 
Create Date: 2026-04-15 22:24:52.606023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector

# revision identifiers, used by Alembic.
revision: str = '3eaaee4c0cc5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blockchain_audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ref_id', sa.Integer(), nullable=False),
    sa.Column('ref_type', sa.String(length=50), nullable=False, comment='attendance|manual_override|org_onboard|user_enroll|key_revoke'),
    sa.Column('record_hash', sa.String(length=64), nullable=False, comment="SHA-256 hex — pgcrypto encode(digest(),'hex')"),
    sa.Column('tx_hash', sa.String(length=128), nullable=True),
    sa.Column('block_number', sa.BigInteger(), nullable=True),
    sa.Column('anchored_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.CheckConstraint("ref_type IN ('attendance','manual_override','org_onboard','user_enroll','key_revoke')", name='ck_blockchain_ref_type'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blockchain_audit_logs_anchored_at'), 'blockchain_audit_logs', ['anchored_at'], unique=False)
    op.create_index(op.f('ix_blockchain_audit_logs_id'), 'blockchain_audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_blockchain_audit_logs_ref_id'), 'blockchain_audit_logs', ['ref_id'], unique=False)
    op.create_index(op.f('ix_blockchain_audit_logs_ref_type'), 'blockchain_audit_logs', ['ref_type'], unique=False)
    op.create_index('ix_blockchain_ref', 'blockchain_audit_logs', ['ref_type', 'ref_id'], unique=False)
    op.create_table('organizations',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('legal_id', sa.String(length=100), nullable=False),
    sa.Column('blockchain_root_key', sa.String(length=255), nullable=True),
    sa.Column('zkp_threshold', sa.Numeric(precision=4, scale=2), server_default=sa.text('0.98'), nullable=False),
    sa.Column('is_active', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('legal_id')
    )
    op.create_index(op.f('ix_organizations_name'), 'organizations', ['name'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False, comment='Admin | Manager | Employee | Device'),
    sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('departments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='0=active, 1=soft-deleted'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.CheckConstraint('is_deleted IN (0, 1)', name='ck_dept_is_deleted'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_departments_active', 'departments', ['org_id'], unique=False, postgresql_where=sa.text('is_deleted = 0'))
    op.create_index(op.f('ix_departments_id'), 'departments', ['id'], unique=False)
    op.create_index(op.f('ix_departments_name'), 'departments', ['name'], unique=False)
    op.create_index(op.f('ix_departments_org_id'), 'departments', ['org_id'], unique=False)
    op.create_table('org_api_keys',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('key_hash', sa.String(length=255), nullable=False, comment='SHA-256 of raw key — pgcrypto digest()'),
    sa.Column('scope', sa.String(length=50), server_default=sa.text("'write_checkin'"), nullable=False),
    sa.Column('rate_limit', sa.Integer(), server_default=sa.text('100'), nullable=False),
    sa.Column('is_revoked', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.CheckConstraint('is_revoked IN (0, 1)', name='ck_api_key_revoked'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    op.create_index('ix_org_api_keys_active', 'org_api_keys', ['key_hash'], unique=False, postgresql_where=sa.text('is_revoked = 0'))
    op.create_index(op.f('ix_org_api_keys_id'), 'org_api_keys', ['id'], unique=False)
    op.create_index(op.f('ix_org_api_keys_org_id'), 'org_api_keys', ['org_id'], unique=False)
    op.create_table('shifts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('shift_name', sa.String(length=100), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('grace_period_mins', sa.Integer(), server_default=sa.text('5'), nullable=False, comment="Minutes after start before 'Late'"),
    sa.Column('buffer_mins', sa.Integer(), server_default=sa.text('15'), nullable=False, comment='Minutes before start for early clock-in'),
    sa.Column('break_deduct_mins', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_deleted', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.CheckConstraint('grace_period_mins >= 0', name='ck_shifts_grace'),
    sa.CheckConstraint('is_deleted IN (0, 1)', name='ck_shifts_is_deleted'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shifts_id'), 'shifts', ['id'], unique=False)
    op.create_index(op.f('ix_shifts_org_id'), 'shifts', ['org_id'], unique=False)
    op.create_table('offline_sync_queue',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_key_id', sa.Integer(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('synced', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='0=pending 1=synced'),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_msg', sa.Text(), nullable=True),
    sa.CheckConstraint('synced IN (0,1)', name='ck_sync_synced'),
    sa.ForeignKeyConstraint(['device_key_id'], ['org_api_keys.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_offline_sync_queue_captured_at'), 'offline_sync_queue', ['captured_at'], unique=False)
    op.create_index(op.f('ix_offline_sync_queue_device_key_id'), 'offline_sync_queue', ['device_key_id'], unique=False)
    op.create_index(op.f('ix_offline_sync_queue_id'), 'offline_sync_queue', ['id'], unique=False)
    op.create_index('ix_sync_queue_pending', 'offline_sync_queue', ['captured_at'], unique=False, postgresql_where=sa.text('synced = 0'))
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('dept_id', sa.Integer(), nullable=True),
    sa.Column('shift_id', sa.Integer(), nullable=True),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('employee_id', sa.String(length=50), nullable=False, comment='HR / payroll reference code'),
    sa.Column('enrollment_token', sa.String(length=255), server_default=sa.text("encode(gen_random_bytes(32), 'hex')"), nullable=True, comment='pgcrypto gen_random_bytes — one-time ZKP onboarding link'),
    sa.Column('token_expires', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False, comment='bcrypt passlib — mirrors pgcrypto crypt()'),
    sa.Column('is_deleted', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='0=active 1=soft-deleted'),
    sa.Column('is_active', sa.Integer(), server_default=sa.text('1'), nullable=False, comment='1=active 0=suspended'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.CheckConstraint('is_active IN (0, 1)', name='ck_users_is_active'),
    sa.CheckConstraint('is_deleted IN (0, 1)', name='ck_users_is_deleted'),
    sa.ForeignKeyConstraint(['dept_id'], ['departments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_active_org', 'users', ['org_id'], unique=False, postgresql_where=sa.text('is_deleted = 0'))
    op.create_index(op.f('ix_users_dept_id'), 'users', ['dept_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_employee_id'), 'users', ['employee_id'], unique=True)
    op.create_index(op.f('ix_users_enrollment_token'), 'users', ['enrollment_token'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index('ix_users_org_email', 'users', ['org_id', 'email'], unique=False)
    op.create_index(op.f('ix_users_org_id'), 'users', ['org_id'], unique=False)
    op.create_index(op.f('ix_users_role_id'), 'users', ['role_id'], unique=False)
    op.create_index(op.f('ix_users_shift_id'), 'users', ['shift_id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('attendance_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('check_in', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('check_out', sa.DateTime(timezone=True), nullable=True, comment='NULL until clock-out'),
    sa.Column('status', sa.String(length=30), nullable=False, comment='on_time|late|early|absent|excused|manual_override'),
    sa.Column('emotion', sa.String(length=30), nullable=True),
    sa.Column('emotion_score', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('is_live', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='1=liveness passed'),
    sa.Column('recognition_distance', sa.Numeric(precision=6, scale=4), nullable=True, comment='pgvector cosine distance at match'),
    sa.Column('source', sa.String(length=20), server_default=sa.text("'ai'"), nullable=False, comment='ai|manual|edge|bulk_import'),
    sa.Column('geofence_pass', sa.Integer(), nullable=True),
    sa.Column('gps_lat', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('gps_lng', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('is_deleted', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.CheckConstraint("source IN ('ai','manual','edge','bulk_import')", name='ck_attendance_source'),
    sa.CheckConstraint("status IN ('on_time','late','early','absent','excused','manual_override')", name='ck_attendance_status'),
    sa.CheckConstraint('is_deleted IN (0,1)', name='ck_attendance_is_deleted'),
    sa.CheckConstraint('is_live IN (0,1)', name='ck_attendance_is_live'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_attendance_checkin_brin', 'attendance_logs', ['check_in'], unique=False, postgresql_using='brin')
    op.create_index(op.f('ix_attendance_logs_check_in'), 'attendance_logs', ['check_in'], unique=False)
    op.create_index(op.f('ix_attendance_logs_id'), 'attendance_logs', ['id'], unique=False)
    op.create_index(op.f('ix_attendance_logs_user_id'), 'attendance_logs', ['user_id'], unique=False)
    op.create_index('ix_attendance_user_checkin', 'attendance_logs', ['user_id', 'check_in'], unique=False, postgresql_where=sa.text('is_deleted = 0'))
    op.create_table('face_embeddings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=128), nullable=False, comment='FaceNet 128-d — pgvector VECTOR(128)'),
    sa.Column('zkp_public_commitment', sa.String(length=512), nullable=True, comment='Schnorr P=x·G — no raw biometric stored'),
    sa.Column('model_name', sa.String(length=50), server_default=sa.text("'Facenet'"), nullable=False),
    sa.Column('is_active', sa.Integer(), server_default=sa.text('1'), nullable=False, comment='1=current 0=superseded by re-enrollment'),
    sa.Column('enrolled_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.CheckConstraint('is_active IN (0, 1)', name='ck_face_embed_is_active'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_face_embeddings_active_user', 'face_embeddings', ['user_id'], unique=False, postgresql_where=sa.text('is_active = 1'))
    op.create_index(op.f('ix_face_embeddings_id'), 'face_embeddings', ['id'], unique=False)
    op.create_index(op.f('ix_face_embeddings_user_id'), 'face_embeddings', ['user_id'], unique=False)
    op.create_table('monthly_growth_summary',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('month_year', sa.String(length=7), nullable=False, comment="'2026-03'"),
    sa.Column('total_present', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('total_late', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('total_absent', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('total_manual', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('avg_emotion_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('stress_event_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('burnout_risk_score', sa.Numeric(precision=5, scale=2), nullable=True, comment='>40 triggers AI Nudge'),
    sa.Column('productivity_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('growth_index', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'month_year', name='uq_monthly_user_month')
    )
    op.create_index('ix_monthly_burnout_risk', 'monthly_growth_summary', ['burnout_risk_score'], unique=False, postgresql_where=sa.text('burnout_risk_score > 40'))
    op.create_index(op.f('ix_monthly_growth_summary_id'), 'monthly_growth_summary', ['id'], unique=False)
    op.create_index(op.f('ix_monthly_growth_summary_user_id'), 'monthly_growth_summary', ['user_id'], unique=False)
    op.create_table('manual_overrides',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('target_user_id', sa.Integer(), nullable=False),
    sa.Column('admin_user_id', sa.Integer(), nullable=False),
    sa.Column('attendance_log_id', sa.Integer(), nullable=True),
    sa.Column('reason_category', sa.String(length=100), nullable=False),
    sa.Column('override_status', sa.String(length=30), nullable=False),
    sa.Column('override_notes', sa.Text(), nullable=True),
    sa.Column('employee_approved', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='0=pending ZKP approval 1=approved'),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.CheckConstraint("reason_category IN ('device_malfunction','forgot_phone','network_outage','camera_failure','admin_correction','other')", name='ck_override_reason'),
    sa.CheckConstraint('employee_approved IN (0,1)', name='ck_override_approved'),
    sa.ForeignKeyConstraint(['admin_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['attendance_log_id'], ['attendance_logs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manual_overrides_admin_user_id'), 'manual_overrides', ['admin_user_id'], unique=False)
    op.create_index(op.f('ix_manual_overrides_attendance_log_id'), 'manual_overrides', ['attendance_log_id'], unique=False)
    op.create_index(op.f('ix_manual_overrides_id'), 'manual_overrides', ['id'], unique=False)
    op.create_index(op.f('ix_manual_overrides_target_user_id'), 'manual_overrides', ['target_user_id'], unique=False)
    op.create_index('ix_override_pending', 'manual_overrides', ['target_user_id'], unique=False, postgresql_where=sa.text('employee_approved = 0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_override_pending', table_name='manual_overrides', postgresql_where=sa.text('employee_approved = 0'))
    op.drop_index(op.f('ix_manual_overrides_target_user_id'), table_name='manual_overrides')
    op.drop_index(op.f('ix_manual_overrides_id'), table_name='manual_overrides')
    op.drop_index(op.f('ix_manual_overrides_attendance_log_id'), table_name='manual_overrides')
    op.drop_index(op.f('ix_manual_overrides_admin_user_id'), table_name='manual_overrides')
    op.drop_table('manual_overrides')
    op.drop_index(op.f('ix_monthly_growth_summary_user_id'), table_name='monthly_growth_summary')
    op.drop_index(op.f('ix_monthly_growth_summary_id'), table_name='monthly_growth_summary')
    op.drop_index('ix_monthly_burnout_risk', table_name='monthly_growth_summary', postgresql_where=sa.text('burnout_risk_score > 40'))
    op.drop_table('monthly_growth_summary')
    op.drop_index(op.f('ix_face_embeddings_user_id'), table_name='face_embeddings')
    op.drop_index(op.f('ix_face_embeddings_id'), table_name='face_embeddings')
    op.drop_index('ix_face_embeddings_active_user', table_name='face_embeddings', postgresql_where=sa.text('is_active = 1'))
    op.drop_table('face_embeddings')
    op.drop_index('ix_attendance_user_checkin', table_name='attendance_logs', postgresql_where=sa.text('is_deleted = 0'))
    op.drop_index(op.f('ix_attendance_logs_user_id'), table_name='attendance_logs')
    op.drop_index(op.f('ix_attendance_logs_id'), table_name='attendance_logs')
    op.drop_index(op.f('ix_attendance_logs_check_in'), table_name='attendance_logs')
    op.drop_index('ix_attendance_checkin_brin', table_name='attendance_logs', postgresql_using='brin')
    op.drop_table('attendance_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_shift_id'), table_name='users')
    op.drop_index(op.f('ix_users_role_id'), table_name='users')
    op.drop_index(op.f('ix_users_org_id'), table_name='users')
    op.drop_index('ix_users_org_email', table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_enrollment_token'), table_name='users')
    op.drop_index(op.f('ix_users_employee_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_dept_id'), table_name='users')
    op.drop_index('ix_users_active_org', table_name='users', postgresql_where=sa.text('is_deleted = 0'))
    op.drop_table('users')
    op.drop_index('ix_sync_queue_pending', table_name='offline_sync_queue', postgresql_where=sa.text('synced = 0'))
    op.drop_index(op.f('ix_offline_sync_queue_id'), table_name='offline_sync_queue')
    op.drop_index(op.f('ix_offline_sync_queue_device_key_id'), table_name='offline_sync_queue')
    op.drop_index(op.f('ix_offline_sync_queue_captured_at'), table_name='offline_sync_queue')
    op.drop_table('offline_sync_queue')
    op.drop_index(op.f('ix_shifts_org_id'), table_name='shifts')
    op.drop_index(op.f('ix_shifts_id'), table_name='shifts')
    op.drop_table('shifts')
    op.drop_index(op.f('ix_org_api_keys_org_id'), table_name='org_api_keys')
    op.drop_index(op.f('ix_org_api_keys_id'), table_name='org_api_keys')
    op.drop_index('ix_org_api_keys_active', table_name='org_api_keys', postgresql_where=sa.text('is_revoked = 0'))
    op.drop_table('org_api_keys')
    op.drop_index(op.f('ix_departments_org_id'), table_name='departments')
    op.drop_index(op.f('ix_departments_name'), table_name='departments')
    op.drop_index(op.f('ix_departments_id'), table_name='departments')
    op.drop_index('ix_departments_active', table_name='departments', postgresql_where=sa.text('is_deleted = 0'))
    op.drop_table('departments')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_organizations_name'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index('ix_blockchain_ref', table_name='blockchain_audit_logs')
    op.drop_index(op.f('ix_blockchain_audit_logs_ref_type'), table_name='blockchain_audit_logs')
    op.drop_index(op.f('ix_blockchain_audit_logs_ref_id'), table_name='blockchain_audit_logs')
    op.drop_index(op.f('ix_blockchain_audit_logs_id'), table_name='blockchain_audit_logs')
    op.drop_index(op.f('ix_blockchain_audit_logs_anchored_at'), table_name='blockchain_audit_logs')
    op.drop_table('blockchain_audit_logs')
    # ### end Alembic commands ###
